#!/usr/bin/env bash

PROFILE_NAME=$1

if [ -z "$PROFILE_NAME" ]; then
    echo "Usage: $0 <profile-name>"
    exit 1
fi

export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id --profile $PROFILE_NAME)
export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key --profile $PROFILE_NAME)
export AWS_DEFAULT_REGION=$(aws configure get region --profile $PROFILE_NAME)

echo "Exported AWS credentials for profile $PROFILE_NAME"
